version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "ThisIsAStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "15433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $SA_PASSWORD -Q 'SELECT 1'"]
      interval: 10s
      retries: 5

  backend:
    image: rrezart/simple-task-manager-api:latest
    container_name: backend
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=MyDb;User Id=sa;Password=ThisIsAStrongPassword123!;TrustServerCertificate=True;"
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "55000:80"

  frontend:
    image: rrezart/simple-task-manager-app:latest
    container_name: frontend
    environment:
      VITE_API_BASE_URL: "http://localhost:55000"
    ports:
      - "33000:3000"
