version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "ThisIsAStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "15433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $SA_PASSWORD -Q 'SELECT 1'"]
      interval: 5s
      retries: 10

  backend:
    image: rrezart/simple-task-manager-api:latest
    container_name: backend
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,15433;Database=MyDb;User Id=sa;Password=ThisIsAStrongPassword123!;TrustServerCertificate=True;"
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "55000:8080"

  frontend:
    image: rrezart/simple-task-manager-app:latest
    container_name: frontend
    environment:
      VITE_API_BASE_URL: "http://localhost:55000"
    ports:
      - "33000:80"
    command: >
      /bin/sh -c "echo \"window.env = { VITE_API_BASE_URL: '$$VITE_API_BASE_URL' };\" > /usr/share/nginx/html/env.js
      && nginx -g 'daemon off;'"
