version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Str0ng!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  backend:
    image: rrezart/simple-task-manager-api:latest
    container_name: backend
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=master;User Id=sa;Password=Str0ng!Pass123;TrustServerCertificate=True;"
    ports:
      - "55000:8080"
    depends_on:
      - sqlserver

  frontend:
    image: rrezart/simple-task-manager-app:latest
    container_name: frontend
    environment:
      VITE_API_BASE_URL: "http://localhost:55000"
    ports:
      - "33000:80"
    command: >
      /bin/sh -c "echo \"window.env = { VITE_API_BASE_URL: '$$VITE_API_BASE_URL' };\" > /usr/share/nginx/html/env.js && ls -l /usr/share/nginx/html && nginx -g 'daemon off;'"
